myproject/myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("shopping/", include('shopping_list.urls')),
    path("admin/", admin.site.urls),
]

myproject/shopping_list/urls.py
from django.urls import path

from . import views

app_name = 'shopping_list'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:itemId>/', views.detail, name='detail'),
    path('add/', views.add, name='add'),
    path('view/', views.view, name='view'),
]

myproject/shopping_list/models.py
from django.db import models


# Create your models here.
class ShoppingListItem(models.Model):
    itemName = models.CharField(max_length=256)
    itemPrice = models.IntegerField()

    def __str__(self):
        return self.itemName

myproject/shopping_list/views.py
from django.http import HttpResponse
from .models import ShoppingListItem
from django.shortcuts import render, get_object_or_404


# Create your views here.
def index(request):
    return render(request, 'shopping_list/index.html')


def add(request):
    return HttpResponse("Add page")


def view(request):
    shoppingList = ShoppingListItem.objects.order_by("id")
    context = {'shoppingList': shoppingList}
    return render(request, 'shopping_list/view.html', context)


def detail(request, itemId):
    item = get_object_or_404(ShoppingListItem, pk=itemId)
    context = {'item': item}
    return render(request, 'shopping_list/detail.html', context)

myproject/shopping_list/templates/shopping_list/detail.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}

<h2>Item Name:</h2>
<p>{{item.itemName}}</p>

<h2>Item price:</h2>
<p>£{{item.itemPrice}}</p>
{% endblock %}

myproject/shopping_list/templates/shopping_list/index.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
<a href="{% url 'shopping_list:view' %}">
  Click here to view the shopping list
</a>
{% endblock %}

myproject/shopping_list/templates/shopping_list/view.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}

<h1>Shopping List</h1>
{% if shoppingList %}
<ul>
  {% for q in shoppingList %}
  <li><a href="{% url 'shopping_list:detail' q.id %}">{{q.itemName}}</a></li>
  {% endfor %}
</ul>
{% else %}
<h1>empty shopping list</h1>
<a href="{% url 'shopping_list:add' %}">click here to add new items</a>
{% endif %} {% endblock %}

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load django_bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <title>My Porject</title>
  </head>
  <body>
    {% block content %} {% endblock content %}
  </body>
</html>